# Generated by Django 5.2 on 2025-04-12 05:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('primary_path', models.CharField(max_length=100)),
                ('alternative_paths', models.JSONField()),
                ('required_skills', models.JSONField()),
                ('growth_potential', models.TextField()),
                ('recommended_steps', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewPrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_title', models.CharField(max_length=100)),
                ('common_questions', models.JSONField()),
                ('suggested_answers', models.JSONField()),
                ('preparation_tips', models.TextField()),
                ('company_research', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobMarketInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('industry', models.CharField(max_length=100)),
                ('demand_score', models.FloatField()),
                ('salary_range', models.JSONField()),
                ('top_locations', models.JSONField()),
                ('trending_skills', models.JSONField()),
                ('job_outlook', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyzed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('strength_score', models.FloatField()),
                ('weaknesses', models.JSONField()),
                ('suggestions', models.JSONField()),
                ('keyword_analysis', models.JSONField()),
                ('improvement_plan', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('technical_skills', models.JSONField()),
                ('soft_skills', models.JSONField()),
                ('interests', models.JSONField()),
                ('strengths', models.JSONField()),
                ('areas_to_improve', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
